### ISSUE TITLE
Script must fail with exit code != 0 in case some error occured during generation or some types were ignored

### ISSUE THREAD

**Issue by vasily-khodyrev** [devexperts/gwtscript#5]
At the moment there's not way to automatically detect that the generation has failed. Please return exitCode(-1) in case there were any issues.

**Comment by Astroner** [comment]
Fixed in this PR:
https://github.com/devexperts/gwtscript/pull/7

**Comment by Astroner** [comment]
Fixed in https://github.com/devexperts/gwtscript/pull/7

**Comment by Astroner** [comment]
aaa
